---
- hosts: authority-ns
  tasks:
  - name: Activate delay on cache <-> name server link
    become: yes
    become_method: sudo
    command:
     tc qdisc add dev eth2 root netem delay 20ms 5ms

- hosts: cache-ns
  tasks:
  - name: Activate delay on client <-> cache link
    become: yes
    become_method: sudo
    command:
     tc qdisc add dev eth1 root netem delay 35ms 5ms


